apiVersion: v1
kind: Service
metadata:
  name: mct-qa-records-api-service
  annotations:
    cloud.google.com/app-protocols: '{"mct-qa-port":"HTTPS"}'
  namespace: dev
spec:
  # type: NodePort
  type: NodePort
  selector:
    app: mct-qa-records-api
  ports:  
  - name: mct-qa-port 
    port: 443
    targetPort: 443
    protocol: TCP