kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mct-regionalpd-storageclass
  namespace: dev
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - us-west1-a
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mct-postgresql-pv
  namespace: dev
spec:
  storageClassName: mct-regionalpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi